/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import * as THREE from "three";

export default function Model(props) {
  const { nodes } = useGLTF("/models/tomas-smol.glb");
  return (
    <group {...props} dispose={null} scale={2.5} rotation={[0, Math.PI / 4, 0]}>
      {props.children}
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={new THREE.MeshNormalMaterial()}
      />
    </group>
  );
}

useGLTF.preload("/models/tomas-smol.glb");
