/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Models = (props) => {
  const { nodes } = useGLTF("/models/models.glb");

  return (
    <group
      {...props}
      dispose={null}
      scale={2}
      rotation={[0, Math.PI, 0]}
      position={[0, 1, 0]}
    >
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
};

useGLTF.preload("/poly.glb");

export default Models;
