/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Paulina(props) {
  const { nodes, materials } = useGLTF('/models/paulina.glb')
  return (
    <group {...props} dispose={null} scale={3} rotation={[0,Math.PI,0]} position={[0,1,0]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/paulina.glb')

export default Paulina;