/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import * as THREE from "three";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/tomas-smol.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={2.5}
      rotation={[0, (2 * Math.PI) / 3, 0]}
      position={[0.2, 1.2, 0]}
    >
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={new THREE.MeshNormalMaterial()}
      />
    </group>
  );
}

useGLTF.preload("/models/tomas-smol.glb");
